version: "3.9"
services:
    redis:
        container_name: kit-redis
        hostname: redis
        networks:
            - server-network
        image: redis
        ports:
            - 6379:6379
        command: ["sh", "-c", "exec redis-server --requirepass \"password\""]

    postgres:
        ports:
            - "5432:5432"
        container_name: kit-postgres
        image: postgres:latest
        restart: always
        networks:
            - server-network
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - ./docker/postgres:/var/lib/postgresql/data
            - ./docker/postgres:/dumps

    nginx:
        image: nginx:alpine
        container_name: kit-nginx
        working_dir: /
        volumes:
            - ./:/kit
            - ./docker/nginx:/etc/nginx/conf.d
        ports:
            - "80:80"
        networks:
            - server-network

    php-82:
        build: docker/php
        container_name: kit-php
        working_dir: /
        volumes:
            - ./:/kit
        networks:
            - server-network

networks:
    server-network:
        external: true
